### ISSUE TITLE
installation instructions

### ISSUE THREAD

**Issue by npomfret** [alcat2008/react-native-auto-expanding-textinput#3]
Thanks for writing this component. I had to run `npm install react-addons-pure-render-mixin --save` to get this to work.  Maybe this should be added to the instructions.

**Comment by alcat2008** [comment]
@npomfret  the modules needed has already been added to peerDependencies, 

```
"peerDependencies": {
    "react": "^15.1.0",
    "react-addons-pure-render-mixin": "^15.1.0",
    "react-native": "^0.27.2"
  },
```

maybe you should check your npm log first.

**Comment by alcat2008** [comment]
@npomfret did the detail above cover your requirements? Can this ticket be closed?

**Comment by npomfret** [comment]
I didn't get a chance to look yet.  But please close, I'll reopen if i can reproduce it.
